### ISSUE TITLE
`dashIndexFilePath` is garbage for virtual manifests

### ISSUE THREAD

**Issue by lilyball** [Robzz/cargo-docset#36]
**Describe the bug**
When building with current `master` (3e2c9b3b6e9af132bd6f261da6c4eb67f6f8604d), if I'm documenting a workspace with a virtual manifest, the `dashIndexFilePath` key in the docset's Info.plist is garbage. The resulting value appears to be the first entry in the `members` list with `/index.html` tacked on.

In my case, my manifest has

```toml
members = [
    "crates/*", "crates-alt/*", "examples/*",
]
```

And the `dashIndexFilePath` of the resulting docset is `crates/*/index.html`.

**To Reproduce**
1. Run `cargo-docset` in a workspace that has a virtual manifest with multiple entries in `members`.

**Expected behavior**
By default, it shouldn't have a `dashIndexFilePath` at all, since there's no index file for docs built from a virtual manifest. If I passed `RUSTDOCFLAGS='-Z unstable-options --enable-index-page'` (or `--index-page PATH`) then it would ideally be set to the resulting `index.html` page instead.

**Comment by Robzz** [comment]
It's been a while since I wrote this but yeah from what I can see, the virtual manifest case was a bit of an afterthought, it does exactly what you say, try and use the first entry in the list of members as a default name for the docset, and as the docset index page, which is obviously not great.

Regarding `RUSTDOCFLAGS='-Z unstable-options --enable-index-page'`, I'll need to look into that, that's probably for another PR (I opened #38 to track it), but thanks for pointing it out.

I pushed #37 which does not add a `dashIndexFilePath` entry when building from virtual manifests. Adding an option to specify which package to use as the index is a good suggestion, I'll do that before merging. I'll probably need to add a second one to allow specifying the docset name.
